import { Product } from './store';

export const products: Product[] = [
  // ── WALLETS ──────────────────────────────────────────────────────────
  {
    id: 'w-001',
    name: 'Pharaoh Bifold Wallet',
    price: 1299,
    originalPrice: 1599,
    image: '/images/product-1.jpg',
    images: [
      '/images/product-2.jpeg',
      '/images/product-3.jpeg',
    ],
    category: 'wallets',
    badge: 'sale',
    rating: 4.9,
    reviews: 127,
    description: 'Crafted from full-grain leather with hand-tooled hieroglyphic patterns. The Pharaoh Bifold is a statement of heritage and luxury.',
    details: ['Full-grain Italian leather', 'Hand-tooled hieroglyphic motifs', '8 card slots + 2 currency pockets', 'RFID-blocking technology', 'Signature AG gold embossing'],
    colors: ['Obsidian', 'Desert Sand', 'Sienna'],
    stock: 42,
    featured: true,
  },
  {
    id: 'w-002',
    name: 'Nile Cardholder',
    price: 649,
    image: '/images/product-4.jpg',
    category: 'wallets',
    badge: 'new',
    rating: 4.8,
    reviews: 84,
    description: 'Minimalist slim cardholder inspired by ancient Egyptian papyrus scrolls.',
    details: ['Vegetable-tanned leather', 'Holds up to 6 cards', 'Slim 5mm profile', 'Interior grip slot'],
    colors: ['Obsidian', 'Papyrus', 'Lapis'],
    stock: 88,
    featured: true,
  },
  {
    id: 'w-003',
    name: 'Sphinx Zip-Around Wallet',
    price: 1849,
    image: '/images/product-5.jpg',
    category: 'wallets',
    rating: 4.7,
    reviews: 53,
    description: 'A full-size travel companion with Egyptian geometry engraving and zipper closure.',
    details: ['Full-size zip-around design', 'Crocodile-embossed leather', '12 card slots', 'Coin purse & ID window', 'Hand-stitched border'],
    colors: ['Obsidian', 'Ruby'],
    stock: 20,
  },
  {
    id: 'w-004',
    name: 'Obelisk Money Clip',
    price: 499,
    image: '/images/product-6.jpg',
    category: 'wallets',
    badge: 'new',
    rating: 4.6,
    reviews: 39,
    description: 'Solid brass money clip with etched obelisk motif and genuine leather backing.',
    details: ['Solid brass construction', 'Genuine leather backing', 'Obelisk etch design', 'Holds up to 15 bills'],
    colors: ['Gold', 'Antique Bronze'],
    stock: 65,
  },

  // ── BAGS ─────────────────────────────────────────────────────────────
  {
    id: 'b-001',
    name: 'Anubis Leather Tote',
    price: 3499,
    originalPrice: 4200,
    image: '/images/product-7.jpg',
    images: [
      '/images/product-8.jpg',
      '/images/product-9.jpg',
    ],
    category: 'bags',
    badge: 'sale',
    rating: 4.9,
    reviews: 218,
    description: 'Our flagship structured tote, hand-stitched in Florence with iconic Anubis silhouette hardware.',
    details: ['Structured full-grain leather', 'Anubis gold-tone hardware', 'Interior laptop sleeve (up to 15")', 'Detachable card pouch', 'Dust bag included'],
    colors: ['Obsidian', 'Cognac', 'Sage'],
    stock: 15,
    featured: true,
  },
  {
    id: 'b-002',
    name: 'Khepri Crossbody',
    price: 2199,
    image: '/images/product-1.jpg',
    category: 'bags',
    badge: 'new',
    rating: 4.8,
    reviews: 143,
    description: 'Compact crossbody with scarab beetle clasp. Day to night effortlessly.',
    details: ['Pebbled leather exterior', 'Scarab beetle magnetic clasp', 'Adjustable/detachable strap', 'Suede lining', 'Zip pocket + 2 slip pockets'],
    colors: ['Obsidian', 'Desert Sand', 'Burgundy'],
    stock: 34,
    featured: true,
  },
  {
    id: 'b-003',
    name: 'Horus Weekend Duffel',
    price: 4750,
    image: '/images/product-2.jpeg',
    category: 'bags',
    rating: 4.9,
    reviews: 72,
    description: 'Weekend-ready duffel crafted from water-resistant full-grain leather with Horus eye emblem.',
    details: ['Water-resistant leather', 'Horus eye brass emblem', 'Shoe compartment', 'Top carry handles + shoulder strap', 'TSA-approved lock'],
    colors: ['Obsidian', 'Dark Tan'],
    stock: 11,
  },
  {
    id: 'b-004',
    name: 'Ra Backpack',
    price: 3100,
    image: '/images/product-3.jpeg',
    category: 'bags',
    badge: 'new',
    rating: 4.7,
    reviews: 96,
    description: 'Structured leather backpack with sun disc embossing and padded tech compartment.',
    details: ['Structured pebbled leather', 'Sun disc back panel emboss', 'Padded 15" laptop sleeve', 'External water bottle pocket', 'Hidden back security pocket'],
    colors: ['Obsidian', 'Dark Olive'],
    stock: 29,
  },

  // ── BELTS ─────────────────────────────────────────────────────────────
  {
    id: 'bl-001',
    name: 'Pharaoh Gold Buckle Belt',
    price: 899,
    image: '/images/product-4.jpg',
    category: 'belts',
    badge: 'new',
    rating: 4.9,
    reviews: 189,
    description: 'Premium full-grain leather belt with 24-karat gold-plated pharaoh head buckle.',
    details: ['Full-grain leather strap', '24k gold-plated buckle', 'Pharaoh head relief design', 'Available in 5 lengths', 'Double-punched holes for perfect fit'],
    sizes: ['85cm', '90cm', '95cm', '100cm', '105cm', '110cm'],
    colors: ['Obsidian', 'Cognac'],
    stock: 78,
    featured: true,
  },
  {
    id: 'bl-002',
    name: 'Eye of Horus Reversible Belt',
    price: 749,
    image: '/images/product-5.jpg',
    category: 'belts',
    rating: 4.7,
    reviews: 112,
    description: 'Reversible black/tan belt with Eye of Horus antique bronze buckle.',
    details: ['Reversible black & tan leather', 'Antique bronze Eye of Horus buckle', 'Rotates 360° for easy reversal', 'Pre-cut to 5 sizes'],
    sizes: ['85cm', '90cm', '95cm', '100cm', '105cm'],
    colors: ['Obsidian/Cognac'],
    stock: 55,
    featured: true,
  },
  {
    id: 'bl-003',
    name: 'Ankh Canvas Belt',
    price: 449,
    image: '/images/product-6.jpg',
    category: 'belts',
    badge: 'sale',
    rating: 4.5,
    reviews: 67,
    description: 'Woven canvas belt with ankh symbol pin buckle. Casual heritage style.',
    details: ['Military-grade woven canvas', 'Ankh pin buckle', 'Adjustable length', 'Lightweight & durable'],
    sizes: ['One Size (adjustable)'],
    colors: ['Desert Tan', 'Obsidian', 'Olive'],
    stock: 120,
  },

  // ── NEW ARRIVALS ───────────────────────────────────────────────────────
  {
    id: 'na-001',
    name: 'Isis Card Sleeve',
    price: 379,
    image: '/images/product-7.jpg',
    category: 'new-arrivals',
    badge: 'new',
    rating: 4.8,
    reviews: 28,
    description: 'Ultra-slim card sleeve with protective goddess wing embossing.',
    details: ['Ultra-slim 3mm profile', 'Holds 4 cards + cash', 'Wing emboss design', 'Vegetable-tanned leather'],
    colors: ['Obsidian', 'Blush', 'Ivory'],
    stock: 200,
    featured: true,
  },
  {
    id: 'na-002',
    name: 'Scarab Mini Bag',
    price: 1650,
    image: '/images/product-8.jpg',
    category: 'new-arrivals',
    badge: 'new',
    rating: 4.9,
    reviews: 14,
    description: 'Micro bag with scarab beetle clasp — the season\'s most coveted accessory.',
    details: ['Structured micro silhouette', 'Scarab beetle jeweled clasp', 'Chain & leather strap combo', 'Velvet lining'],
    colors: ['Obsidian', 'Midnight Blue', 'Emerald'],
    stock: 40,
    featured: true,
  },
  {
    id: 'na-003',
    name: 'Lotus Card Case',
    price: 529,
    image: '/images/product-9.jpg',
    category: 'new-arrivals',
    badge: 'new',
    rating: 4.7,
    reviews: 21,
    description: 'A card case adorned with delicate lotus pattern pressing.',
    details: ['Saffiano leather', 'Lotus flower emboss', '6 card slots', 'Magnetic closure'],
    colors: ['Sand', 'Dusty Rose', 'Teal'],
    stock: 75,
  },
  {
    id: 'na-004',
    name: 'Memphis Tote',
    price: 2799,
    image: '/images/product-1.jpg',
    category: 'new-arrivals',
    badge: 'new',
    rating: 4.8,
    reviews: 9,
    description: 'Oversized tote with Memphis geometry pattern lining — art for the everyday.',
    details: ['Soft pebbled leather', 'Memphis print interior', 'Open top with magnetic snap', 'Inside zip pocket'],
    colors: ['Natural', 'Obsidian'],
    stock: 22,
    featured: true,
  },
];

export const getProductsByCategory = (category: string) =>
  products.filter((p) => p.category === category);

export const getFeaturedProducts = () =>
  products.filter((p) => p.featured);

export const getProductById = (id: string) =>
  products.find((p) => p.id === id);

export const getAllCategories = () => [
  { id: 'wallets', name: 'Wallets', count: products.filter(p => p.category === 'wallets').length },
  { id: 'bags', name: 'Bags', count: products.filter(p => p.category === 'bags').length },
  { id: 'belts', name: 'Belts', count: products.filter(p => p.category === 'belts').length },
  { id: 'new-arrivals', name: 'New Arrivals', count: products.filter(p => p.category === 'new-arrivals').length },
];
